name: go-release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: build
        run: |
          make build/linux
          make build/windows
          make build/mac
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
